### ISSUE TITLE
[(たぶん)不具合] Windowsからだと鍵ファイルのアップロードがエラーになってしまう

### ISSUE THREAD

**Issue by sogaoh** [enshared/issues#10]
[再現手順]
- ファイルをアップロードしてダウンロードURLを採取する（１）
- ダウンロード時に必要になる鍵ファイルを取得（２）
- （１）のURLを共有、（２）の鍵ファイルをメールで共有
- Windows 10 の Chrome でメールから（２）をダウンロード（２’）
- （１）のURLをリクエストして、（２'）の鍵ファイルをアップロード

![key_error](https://user-images.githubusercontent.com/2090887/75950679-32288d80-5eed-11ea-802c-b17c5d16a648.png)

[補足]
- 再現手順と同じことを Mac PC で行った結果は、問題なく鍵ファイルをアップロードできた

**Comment by sogaoh** [comment]
雑なhtmlで MIME type の採取を試みた結果をお知らせします

- Windows: Type (不明)
- Mac : Type application/x-x509-ca-cert

採取に用いたHTMLは以下です

```html

<input type="file" multiple onchange="showType(this)">

<script type="text/javascript">
    function showType(fileInput) {
        var files = fileInput.files;

        for (var i = 0; i < files.length; i++) {
            var name = files[i].name;
            var type = files[i].type;
            alert("Filename: " + name + " , Type: " + type);
        }
    }
</script>
```

出典は https://developer.mozilla.org/ja/docs/Web/API/File/type より。

**Comment by m3m0r7** [comment]
修正が完了しました

**Comment by sogaoh** [comment]
Windowsでの鍵ファイルアップロード成功を確認できました。
修正対応ありがとうございます。これで心おきなくWindowsの人ともやりとりできそうです
