### ISSUE TITLE
削除キーのハイフン入力を許容もしくは数字のみで表記

### ISSUE THREAD

**Issue by tanakahisateru** [enshared/issues#12]
削除キーが 1234-5678(例) と表示され、そのままコピペで保存していても、じっさいに削除キーを入力するときは、UI で 8 桁の数字のみが要求される (ハイフン不要は明記されていない) ので、勝手がよくないです。

ハイフンありなしどちらも許容、または、削除キー表示のさいハイフンなし表記にしておくのが適当ではないかと思います。

**Comment by m3m0r7** [comment]
対応しました
