### ISSUE TITLE
アップロード履歴は論理削除

### ISSUE THREAD

**Issue by tanakahisateru** [enshared/issues#13]
アップロード履歴に「削除した履歴も表示」チェックボックスがあると助かります。上げた記憶はあるけど、消したかな、もしかしてログインしてなかったかな、と不安になるといけないので、ログインしてアップロードしたものをたしかに削除した、と確認できたら安心です。

**Comment by m3m0r7** [comment]
チェックボックス追加まではしていませんが、アップロード履歴に削除済みのアーカイブの一覧を表示するようにしました。 UI はもう少し考えます。
