### ISSUE TITLE
アップロードオプションはタブ  UI が良いのでは

### ISSUE THREAD

**Issue by tanakahisateru** [enshared/issues#14]
アップロードのオプションには使用頻度に偏りがあるので、よく使うものが下のほうにあったり、セットで使うものが離れていたりして、理解/使用がスムーズでない感触があります。

タブ UI にして、たとえばこのようにまとめるのはどうかという提案です。

- 基本
  - 組織を選択 (ログインしている場合のみ enable)
  - (選択した場合 → この組織にのみ公開 enable: 将来)
  - メッセージ
  - パスワード (← わりと使うのでここ)
  - 有効期限
- 制限
  - ダウンロード回数を表示する
  - ダウンロード回数制限
  - -- 分割線 --
  - IPアドレスを制限
- 予約公開
  - 公開予定日時
  - 入力した場合 → 公開日までカウントダウン enable
- セキュリティ
  - 秘密鍵による暗号化
     (秘密鍵が生成されてサーバーサイドで復号できない概要が平文でちらっと書いてある)

完了/失敗通知はアップロード最終確認モーダルダイアログへ

設定しない場合が多い or よりマニアックな理解が必要なものを右タブへやり、最重要で毎回要チェックなものを厳選して、最初から目立ってるようにしてあると、初めてでも「ウッ」ってならずに済むし、慣れてきた人も操作時の移動量が減ってよいと思います。

検討: 「ファイルをアップロード」ボタンはタブの右上へ
前回と同じ設定で繰り返し使う場合に、スクロールしてオプション設定を確認からのサブミットより、アップロード予定ファイルのリストを目視しながらのサブミットをできるほうが親切かな... うーん、近すぎてオプション見ずにうっかり押してしまうかな

**Comment by tanakahisateru** [comment]
「IPアドレスを制限」は固定IPの環境あまりないので「セキュリティ」にまわして、二番目のタブを「DL回数」にするのがスマートかもしれない

**Comment by m3m0r7** [comment]
いったん、「基本設定」「詳細設定」「通知設定」「組織設定」の 4 つに分割しました。
基本設定には普段のユースケースで使われるであろう想定のものを置いています。
詳細設定はそれ以外ですね。
本来はタブの中に縦タブおいて Twitter のように事細かに設定できるようにすべきな気がしますが、現状時間の確保が難しそうであることから、上記のようにしました。

アップロードボタンは従来どおりの位置にしており、これはひさてるさんが言っている理由とほぼ同じの理由で下に置いています。

アップロードするときに、本来であれば各種設定をしてからアップロードしたいと考えるのが自然だと思っています。
設定を終えてから上に戻るという一手間が加わるよりかは現状のほうが、ユーザー体験として良い気がします。

一方でショートカットキーを設定とかは全然ありだとは思います。

**Comment by m3m0r7** [comment]
@tanakahisateru

**Comment by tanakahisateru** [comment]
タブを切り替えたときに入力済みのテキストがクリアされてしまいました。文字入力以外のUIは選択が保持されています。 @m3m0r7

**Comment by tanakahisateru** [comment]
新規バグは新規issueの方がいいかな

**Comment by m3m0r7** [comment]
ウッなんと

**Comment by m3m0r7** [comment]
@tanakahisateru 
> タブを切り替えたときに入力済みのテキストがクリアされてしまいました。文字入力以外のUIは選択が保持されています。
対応完了しました。
