### ISSUE TITLE
[要望] ダウンロード履歴画面を設けてほしい

### ISSUE THREAD

**Issue by sogaoh** [enshared/issues#9]
- いつ
- 誰が(ログインしてれば)
- どこから(public ip)
- なにで(UserAgent ?)

でダウンロードしたのかを確認できるようにしてほしい

[理由]

- 見知らぬ人にダウンロードされていないか、ある程度把握したい（できる範囲で）
- カタイ言い方ですが、証跡残し

**Comment by m3m0r7** [comment]
@sogaoh 
頂いた内容をお答えいたします。

いつ、誰が、どこから、なにでという話で個人情報保護の観点から一部ご提供できないものがあります。
特にグローバル IP アドレスはプロバイダに問い合わせれば個人を特定できてしまうものになってしまうため慎重に取り扱うべき内容となります。

時間帯とどんなブラウザ（UA）でダウンロードしたかでしたら、提供できますがそれでいかがでしょうか？

**Comment by sogaoh** [comment]
@m3m0r7 
コメントありがとうございます。
個人がわからない範囲での提供、の意向は理解できます。

可能であればOSがわかるとありがたいかなとも思いましたが、
それが何かに抵触するようであればそこはお気になさらず、でお願いします。 🙇

**Comment by m3m0r7** [comment]
@sogaoh 
了解です！

**Comment by m3m0r7** [comment]
実装完了しました

**Comment by sogaoh** [comment]
機能確認しました。
対応ありがとうございます 👏
